services:
  - type: web
    name: thesis-backend
    env: node
    plan: free
    rootDir: data-api  # <--- ADD THIS LINE
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0